# Generated by Django 2.2.24 on 2021-06-21 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210621_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 15, 32, 50, 991414, tzinfo=utc)),
        ),
    ]
