# Generated by Django 2.2.24 on 2021-06-21 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210621_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 15, 42, 13, 749994, tzinfo=utc)),
        ),
    ]
