# Generated by Django 3.2.4 on 2021-06-13 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(default='password', max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 6, 13, 10, 0, 19, 782371, tzinfo=utc))),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
