# Generated by Django 2.2.7 on 2021-06-13 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210613_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 10, 22, 33, 9519, tzinfo=utc)),
        ),
    ]
