# Generated by Django 2.2.7 on 2021-06-13 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210613_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 10, 39, 47, 109114, tzinfo=utc)),
        ),
    ]
